name: Main Caller Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  call_reusable_workflow:
    uses: ./.github/workflows/simple-reusable.yml
    with:
      message: "Hello from the main workflow!"
