# name: Simple Reusable Workflow # The name of this reusable workflow.

on:
  workflow_call: # This is the key trigger for a reusable workflow. It means this workflow can only be triggered by another workflow.
    inputs: # Defines the inputs that this reusable workflow expects from its caller.
      message: # The name of the input. This must match the key used in the 'with' section of the caller.
        required: true # Specifies that this input must always be provided by the caller.
        type: string # Defines the data type of the input.
        description: "A message passed from the caller workflow." # A helpful description for anyone using this reusable workflow.

jobs:
  reusable_job: # Defines a job within this reusable workflow.
    runs-on: ubuntu-latest # Specifies the operating system environment for this job.
    steps: # A sequence of tasks to be executed within the job.
      - name: Print the message # A descriptive name for this step.
        run: | # Executes a shell command.
          echo "Message from caller: ${{ inputs.message }}" # Accesses the 'message' input passed from the caller using the `inputs` context.