name: Simple Reusable Workflow

on:
  workflow_call:
    # Define inputs this workflow expects
    inputs:
      message:
        description: 'A message to display'
        required: true
        type: string
      count:
        description: 'A number to count up to'
        required: false
        type: number
        default: 3 # If not provided, defaults to 3

    # Define outputs this workflow can pass back to the caller
    outputs:
      final_status:
        description: 'Status of the reusable workflow run'
        value: ${{ jobs.process_message.outputs.status }} # Reference an output from a job within this workflow

jobs:
  process_message:
    runs-on: ubuntu-latest
    outputs:
      status: ${{ steps.set_output.outputs.result_message }} # Define an output for this job

    steps:
      - name: Display Message and Count
        run: |
          echo "Received message: ${{ inputs.message }}"
          for i in $(seq 1 ${{ inputs.count }}); do
            echo "Counting: $i"
          done

      - name: Set Output Message
        id: set_output # Give this step an ID to reference its outputs
        run: |
          echo "result_message=Reusable workflow completed successfully." >> $GITHUB_OUTPUT