name: Simple Reusable Workflow

on:
  workflow_call:
    inputs:
      message:
        required: true
        type: string
        description: "A message passed from the caller workflow."

jobs:
  reusable_job:
    runs-on: ubuntu-latest
    steps:
      - name: Print the message
        run: |
          echo "Message from caller: ${{ inputs.message }}"
